/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day06manyinputs;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author emmadebarros
 */
public class Day06ManyInputs extends javax.swing.JFrame {

    /**
     * Creates new form Day06ManyInputs
     */
    public Day06ManyInputs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpAge = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbAgeBelow18 = new javax.swing.JRadioButton();
        rbAge18to35 = new javax.swing.JRadioButton();
        rbAge35up = new javax.swing.JRadioButton();
        cbPetCat = new javax.swing.JCheckBox();
        cbPetDog = new javax.swing.JCheckBox();
        cbPetOther = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        comboContinent = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        sliderTemp = new javax.swing.JSlider();
        btRegister = new javax.swing.JButton();
        lblTemp = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Name:");

        jLabel2.setText("Age:");

        jLabel3.setText("Pets:");

        btnGrpAge.add(rbAgeBelow18);
        rbAgeBelow18.setSelected(true);
        rbAgeBelow18.setText("-18");

        btnGrpAge.add(rbAge18to35);
        rbAge18to35.setText("18 - 35");

        btnGrpAge.add(rbAge35up);
        rbAge35up.setText("36+");

        cbPetCat.setText("cat");

        cbPetDog.setText("dog");

        cbPetOther.setText("other");

        jLabel4.setText("Continent:");

        comboContinent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "North America", "South America", "Europe", "Asia", "Africa", "Australia", "Antarctica" }));

        jLabel5.setText("Prefered Temp C:");

        sliderTemp.setMajorTickSpacing(5);
        sliderTemp.setMaximum(35);
        sliderTemp.setMinimum(15);
        sliderTemp.setMinorTickSpacing(1);
        sliderTemp.setPaintLabels(true);
        sliderTemp.setPaintTicks(true);
        sliderTemp.setSnapToTicks(true);
        sliderTemp.setValue(22);
        sliderTemp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTempStateChanged(evt);
            }
        });

        btRegister.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btRegister.setText("Register Me");
        btRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegisterMouseClicked(evt);
            }
        });

        lblTemp.setText("22 C");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbAgeBelow18)
                            .addComponent(cbPetCat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbAge18to35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(rbAge35up)
                                .addGap(68, 68, 68))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbPetDog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbPetOther)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblTemp))
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbAgeBelow18)
                    .addComponent(rbAge18to35)
                    .addComponent(rbAge35up))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPetCat)
                    .addComponent(cbPetDog)
                    .addComponent(cbPetOther))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTemp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sliderTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegisterMouseClicked
        // TODO add your handling code here:

        String name = tfName.getText();

        if (name.isEmpty()) {
            //custom title, error icon
            JOptionPane.showMessageDialog(this,
                    "Name field must not be empty.",
                    "Input error",
                    JOptionPane.ERROR_MESSAGE); // code from : https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html
            return;
        }

        //test System.out.println(name);

        String age;

        /*
        if (rbAge18to35.isSelected() == true) {
            age = "Between 18 and 35";
        } else if (rbAge35up.isSelected() == true) {
            age = "36+";
        } else {
            age = "Under 18";
        }
        */
        if(rbAgeBelow18.isSelected()) {
            age = "Under 18";
        }
        else if(rbAge18to35.isSelected() == true) {
            age = "Between 18 and 35";
        } else if (rbAge35up.isSelected() == true) {
            age = "36+";
        } else { // should never happen
            //custom title, error icon
            JOptionPane.showMessageDialog(this,
                    "Invalid control flow 100034.",
                    "Input error",
                    JOptionPane.ERROR_MESSAGE); // code from : https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html
            return;
        }

        //test System.out.println(age);

        String pet = "No pet"; // see teacher's solution with ArrayList, if, and string.join(", ", arrayList) - more efficient

        if (cbPetCat.isSelected()) {
            if(pet.equals("No pet")) {
                pet = "Cat";
            } else {
                pet += ", Cat";
            }
        }
        
        if (cbPetDog.isSelected()) {
            if(pet.equals("No pet")) {
                pet = "Dog";
            } else {
                pet += ", Dog";
            }
        }
        
        if (cbPetOther.isSelected()) {
            if(pet.equals("No pet")) {
                pet = "Other";
            } else {
                pet += ", Other";
            }
        }
        
        //test System.out.println(pet);
        
        String continent = (String)comboContinent.getSelectedItem(); //cast
        
        //test System.out.println(continent);
        
        String tempC = Integer.toString(sliderTemp.getValue());
        
        //test System.out.println(temp);
        
        try(BufferedWriter bw = new BufferedWriter(new FileWriter("inputs.txt", true))) { // not sure about this part... verif with teacher's code
            bw.append(String.format("%s;%s;%s;%s;%s C\n", name, age, pet, continent, tempC));
        } catch (IOException exc) {
            //custom title, error icon
            JOptionPane.showMessageDialog(this,
                    "There was an error writing the data to file. Please try again.\n" + exc.getMessage(),
                    "Input error",
                    JOptionPane.ERROR_MESSAGE); // code from : https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html
        }
        
        tfName.setText("");
        
    }//GEN-LAST:event_btRegisterMouseClicked

    //event listener on the slider
    private void sliderTempStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTempStateChanged
        // TODO add your handling code here:
        
        int temp = sliderTemp.getValue();
        
        lblTemp.setText(String.format("%d C", temp));
        
    }//GEN-LAST:event_sliderTempStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day06ManyInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day06ManyInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day06ManyInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day06ManyInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day06ManyInputs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegister;
    private javax.swing.ButtonGroup btnGrpAge;
    private javax.swing.JCheckBox cbPetCat;
    private javax.swing.JCheckBox cbPetDog;
    private javax.swing.JCheckBox cbPetOther;
    private javax.swing.JComboBox<String> comboContinent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JRadioButton rbAge18to35;
    private javax.swing.JRadioButton rbAge35up;
    private javax.swing.JRadioButton rbAgeBelow18;
    private javax.swing.JSlider sliderTemp;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
