/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day06helloswing;

import javax.swing.JOptionPane;

/**
 *
 * @author emmadebarros
 */
public class Day06HelloSwing extends javax.swing.JFrame {

    /**
     * Creates new form Day06HelloSwing
     */
    public Day06HelloSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        btSayHelloViaLabel = new javax.swing.JButton();
        btSayHelloViaMsgBox = new javax.swing.JButton();
        lblGreeting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("What is your name?");

        btSayHelloViaLabel.setText("Say Hello (Message Box)");
        btSayHelloViaLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSayHelloViaLabelActionPerformed(evt);
            }
        });

        btSayHelloViaMsgBox.setText("Say Hello (Label)");
        btSayHelloViaMsgBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSayHelloViaMsgBoxActionPerformed(evt);
            }
        });

        lblGreeting.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGreeting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btSayHelloViaMsgBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btSayHelloViaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfName))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSayHelloViaLabel)
                    .addComponent(btSayHelloViaMsgBox))
                .addGap(18, 18, 18)
                .addComponent(lblGreeting)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSayHelloViaMsgBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSayHelloViaMsgBoxActionPerformed
        // TODO add your handling code here:

        String name = tfName.getText();
        //is string empty?

        if (name.isEmpty()) {
            //custom title, error icon
            JOptionPane.showMessageDialog(this,
                    "Name must not be empty.",
                    "Input error",
                    JOptionPane.ERROR_MESSAGE); // code from : https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html
            return; // return statement is similar to if else. Meaning that the rest of the code will not execute if this is true so might as well return from the method.
        }

        String msg = String.format("Hello %s, nice to meet you", name);

        //default title and icon
        JOptionPane.showMessageDialog(this, msg); // code from : https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html

    }//GEN-LAST:event_btSayHelloViaMsgBoxActionPerformed

    private void btSayHelloViaLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSayHelloViaLabelActionPerformed
        // TODO add your handling code here:

        String name = tfName.getText();
        //is string empty?

        if (name.isEmpty()) {
            //custom title, error icon
            JOptionPane.showMessageDialog(this,
                    "Name must not be empty.",
                    "Input error",
                    JOptionPane.ERROR_MESSAGE); // code from : https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html
            return;
        }

        String msg = String.format("Hello %s, nice to meet you", name);
        lblGreeting.setText(msg); // code from : https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html

    }//GEN-LAST:event_btSayHelloViaLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day06HelloSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day06HelloSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day06HelloSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day06HelloSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day06HelloSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSayHelloViaLabel;
    private javax.swing.JButton btSayHelloViaMsgBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
